apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavendeployment
  namespace: demo-ns
spec:
  replicas: 2
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      app: mvnapp
  template:
    metadata:
      name: mavenwebapp
      labels:
        app: mvnapp
    spec:
      containers:
      - name: mavenappcontainer
        image: singhragvendra503/maven_web_application:1.0
        ports:
        - containerPort: 8080
