apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpadeployment
  namespace: demo-ns
spec:
  selector:
    matchLabels:
      name: hpapod
  template:
    metadata:
      labels:
        name: hpapod
    spec:
      containers:
      - name: mavenappcontainer
        image: singhragvendra503/maven-web-application:1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "100m"
            memory: "300Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: hpaservice
  namespace: demo-ns
spec:
  type: LoadBalancer
  selector:
    name: hpapod
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpadeploymentautoscaler
  namespace: demo-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hpadeployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 40
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
