apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpadeployment
spec:
  selector:
    matchLabels:
      name: hpapod
  template:
    metadata:
      labels:
        name: hpapod
    spec:
      containers:
      - name: mavenappcontainer
        image: 049526001344.dkr.ecr.us-west-1.amazonaws.com/first-class-fly-ecr:IMAGE_TAG
        ports:
        - containerPort: 4200
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "100m"
            memory: "300Mi"